version: '3.8'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${HTTP_PORT:-80}:80"
        restart: unless-stopped
        networks:
            - maxmoll-crm

    mysql:
        image: mysql:latest
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - maxmoll-crm

    php:
        container_name: php
        build:
            context: ./_docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        restart: unless-stopped
        networks:
            - maxmoll-crm


networks:
    maxmoll-crm:
        driver: bridge
